### ISSUE TITLE
getting lots of errors in this code

### ISSUE THREAD

**Issue by manwapri** [mkycrb/ethash#1]
make: *** [binary_container_1.build/krnl_vadd.xo] Error 1
v++ 200-70: Compilation errors found: In file included from /root/workspace/ethash3/src/krnl_vadd.cpp:1:
v++ 60-300: Failed to build kernel(ip) krnl_vadd, see log for details: /root/workspace/ethash3/Emulation-SW/binary_container_1.build/krnl_vadd/krnl_vadd/vivado_hls.log
v++ 60-592: Failed to finish compilation
v++ 60-599: Kernel compilation failed to complete
unknown type name 'uint32_t'
expected ';' at end of declaration
function declared in block scope cannot have 'static' storage class
unknown type name 'uint'; did you mean 'int'?
expected expression
use of undeclared identifier 'uint8_t'
expected expression
use of undeclared identifier 'uint8_t'
'inline' can only appear on functions
expected ';' at end of declaration
expected expression
use of undeclared identifier 'uint8_t'
variable has incomplete type 'void'
expected '}'

**Comment by manwapri** [comment]
This issue has been resolved.
import all files in src vitis, delete hardware kernel file, and add hardware kernel file as krnl_ethash.cl

**Comment by shaunclimbon** [comment]
Errors are expected unless you use the same version of tools and same Git tags.  But overall process remains the same.  Also,  ethash is used here as an example of how to _start_ migrating algos (in-general) towards hardware acceleration.  This is not a real/optimized solution.
