### ISSUE TITLE
Where is the cache file?

### ISSUE THREAD

**Issue by hejia-zhang** [mkycrb/ethash#2]
In the tutorial part 3 https://developer.xilinx.com/en/articles/code-busting-fpga-blockchain-myths-part-3.html

Where is the cache file?

**Comment by fallshuang** [comment]
the ethereum light cache file is  only needed to generate DAG file ,  it has nothing to do with miner algo .

**Comment by shaunclimbon** [comment]
thanks for commenting @fallshuang, that pretty much answers it

The testbench app supplied by the ethash repo might use a cache (for validation of the algo) but even then it's not required.
